#!/bin/bash
# SP25 - ISS 212 Week 4 Tool Dev 2
# Works Cited - Jenn Moody
# Tool Dev Scenario 2

echo "System Uptime: $(uptime -p)"
echo "Available Disk Space:"
df -h | grep '^/'
echo "Available RAM:"
free -m | awk 'NR==2{print $7 "MB free"}'


